version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-blogdb}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-blog}
      POSTGRES_USER: ${POSTGRES_USER:-blog}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  pgadminbg:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=blog@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=blog1234
        ports:
            - '5055:80'
        restart: always
        volumes: 
            - pgadmin:/root/.pgadmin

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
  pgadmin:
###< doctrine/doctrine-bundle ###
